import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0a0a0f",
        surface: "#0a0a0f",
        "surface-card": "#12121a",
        "surface-dim": "#0a0a0f",
        "surface-bright": "#0a0a0f",
        "surface-container": "#0a0a0f",
        "surface-container-low": "#0a0a0f",
        "surface-container-high": "#0a0a0f",
        "surface-container-highest": "#0a0a0f",
        "surface-variant": "#36343a",
        primary: "#60a5fa",
        "primary-container": "#3b82f6",
        "primary-fixed": "#bfdbfe",
        "primary-fixed-dim": "#93c5fd",
        "on-primary": "#ffffff",
        "on-primary-container": "#dbeafe",
        "on-primary-fixed": "#1e3a8a",
        "on-primary-fixed-variant": "#1d4ed8",
        secondary: "#cdc0e9",
        "secondary-container": "#4d4465",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#cdc0e9",
        "on-secondary": "#342b4b",
        "on-secondary-container": "#bfb2da",
        "on-secondary-fixed": "#1f1635",
        "on-secondary-fixed-variant": "#4b4263",
        tertiary: "#e7c365",
        "tertiary-container": "#c9a74d",
        "tertiary-fixed": "#ffdf93",
        "tertiary-fixed-dim": "#e7c365",
        "on-tertiary": "#3e2e00",
        "on-tertiary-container": "#503d00",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#594400",
        "on-background": "#e6e0e9",
        "on-surface": "#e6e0e9",
        "on-surface-variant": "#cbc4d2",
        outline: "#948e9c",
        "outline-variant": "#494551",
        "inverse-surface": "#e6e0e9",
        "inverse-on-surface": "#322f35",
        "inverse-primary": "#2563eb",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        subtle: "#1e1e2e",
      },
      fontFamily: {
        rubik: ["var(--font-rubik)", "Rubik", "sans-serif"],
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
        headline: ["var(--font-rubik)", "Rubik", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl": ["var(--font-rubik)", "Rubik", "sans-serif"],
        "headline-lg": ["var(--font-rubik)", "Rubik", "sans-serif"],
        "headline-lg-mobile": ["var(--font-rubik)", "Rubik", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "nav-link": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "nav-link": ["15px", { lineHeight: "1", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        "section-gap": "8rem",
        gutter: "2rem",
        "margin-mobile": "1.25rem",
        "container-max": "800px",
        "element-gap": "1.5rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
